### ISSUE TITLE
plugin needed to handle lto object

### ISSUE THREAD

**Issue by yhyuan** [basilfx/LPC810-FanController#1]
Hi 
When I tried to compile with 
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
The following error is found
arm-none-eabi-ld: lib/lpcopen/src/uart_8xx.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/lpcopen/src/wkt_8xx.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/lpcopen/src/wwdt_8xx.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/1-wire/src/1-Wire.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/1-wire/src/1-WireCRC.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/ds18x20/src/DS18x20.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/pid/src/pid.o: plugin needed to handle lto object
arm-none-eabi-ld: lib/printf/src/printf.o: plugin needed to handle lto object

any clue?

**Comment by basilfx** [comment]
This is probably related to your compiler version. You can see if your compiler is compiled with LTO support (see [here](https://www.reddit.com/r/Gentoo/comments/6b1dlc/plugin_needed_to_handle_lto_object_and_correct/)), or remove `-flto` from the command line (generates larger binary).
